TigardHighGDC/Augmentation

- .gitignore
> Fix for `UserSettings/` ignore

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Issue templates

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
> Unity Version Update `2021.3.16f1`

- .gitmodules
- CONTRIBUTING.md
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
- README.md
> Git submodule a star

- Docs/ChangeLog.md
> Sprint 2 Changelog

- Assets/Prefabs/Player.prefab
> Collider added to player

- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
> Unity Version Update `2021.3.17f1`

- Assets/Prefabs/LaptopGoon.prefab
> LaptopGoon Fix

- Assets/Prefabs/LaptopGoon.prefab
- Assets/Scenes/Nate's Scene.unity
- Assets/Scripts/Enemies/BasicEnemy.cs
- Assets/Scripts/Enemies/EnemyHealth.cs
- Assets/Scripts/Enemies/EnemyHealth.cs.meta
- Assets/Scripts/Enemies/LaptopGoon/LaptopGoonAI.cs
- Assets/Scripts/Player/CorruptionLevel.cs
- Assets/Scripts/Player/CorruptionLevel.cs.meta
- Assets/Scripts/Player/PlayerMovement.cs
> Corruption Level Created

- Docs/ChangeLog.md
> Sprint 3 Changelog

- Assets/Scripts/Weapons/Data/Pistol.asset
- Assets/Scripts/Weapons/Data/WeaponData.cs
- Assets/Scripts/Weapons/ProjectileGun/Gun.cs
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
> Reload sound

- Docs/ChangeLog.md
> Sprint 4 changelog

- Assets/Prefabs/HealthBar.prefab
- Assets/Prefabs/HealthBar.prefab.meta
- Assets/Scripts/Player/PlayerHealth.cs
- Assets/Scripts/SliderBarScript.cs
- Assets/Scripts/SliderBarScript.cs.meta
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
also works for corruption bar Just change a few things
> Health Bar Created

- Assets/Scripts/Environment/SceneLoader.cs
> Async scene loader fix

- Assets/Scripts/Enemies/AIPhysics.cs
- Assets/Scripts/Enemies/Bug/BugAI.cs
- Assets/Scripts/Enemies/EY/EY_AI.cs
- Assets/Scripts/Enemies/EY/EyeTracking.cs
- Assets/Scripts/Enemies/EY/LaserLine.cs
- Assets/Scripts/Enemies/EnemyAI.cs
- Assets/Scripts/Enemies/EnemyDealDamage.cs
- Assets/Scripts/Enemies/EnemyHealth.cs
- Assets/Scripts/Enemies/EnemyProjectile/EnemyBullet.cs
- Assets/Scripts/Enemies/EnemyProjectile/EnemyProjectileData.cs
- Assets/Scripts/Enemies/Hackerman/HackermanAI.cs
- Assets/Scripts/Enemies/Hackerman/MomentumAI.cs
- Assets/Scripts/Enemies/LaptopGoon/LaptopGoonAI.cs
- Assets/Scripts/Player/CorruptionLevel.cs
- Assets/Scripts/Player/PlayerHealth.cs
- Assets/Scripts/Player/PlayerMovement.cs
- Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
- Assets/Scripts/Weapons/ProjectileGun/Gun.cs
> Added copyright to files + small cleanups

- Assets/Scripts/Weapons/Data/AssaultRifle.asset
- Assets/Scripts/Weapons/Data/BigBoy.asset
- Assets/Scripts/Weapons/Data/Pistol.asset
- Assets/Scripts/Weapons/Data/Shotgun.asset
- Assets/Scripts/Weapons/Data/Sniper.asset
- Assets/Scripts/Weapons/Data/WeaponData.cs
- Assets/Scripts/Weapons/ProjectileGun/Gun.cs
Renamed variable to better represent it and sniper value
> Sniper quick change

- Assets/Scripts/Weapons/Data/AssaultRifle.asset
- Assets/Scripts/Weapons/Data/Pistol.asset
- Assets/Scripts/Weapons/Data/Shotgun.asset
- Assets/Scripts/Weapons/Data/Sniper.asset
- Assets/Scripts/Weapons/Data/WeaponData.cs
- Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
> Bullet Pierce

- Assets/Scripts/Item.meta
- Assets/Scripts/Item/ItemHandling.cs
- Assets/Scripts/Item/ItemHandling.cs.meta
- Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
Closes #26 
Basic setup for using EventHandling
> Item Handling

- Assets/Prefabs/Map Objects.prefab
- Assets/Scenes/Basic Enemies.unity
- Assets/Scenes/Basic Enemies.unity.meta
- Assets/Scenes/Boss.unity
- Assets/Scenes/Boss.unity.meta
- Assets/Scenes/Elite Enemies.unity
- Assets/Scenes/Elite Enemies.unity.meta
- Assets/Scenes/MainMenu.unity
- Assets/Scenes/Rest Site.unity
- Assets/Scenes/Rest Site.unity.meta
- Assets/Scenes/Store.unity
- Assets/Scenes/Store.unity.meta
- Assets/Scenes/Treasure.unity
- Assets/Scenes/Treasure.unity.meta
- Assets/Scripts/Map/MapPlayerTracker.cs
- ProjectSettings/EditorBuildSettings.asset
Closes #109.
Currently have 6 different types of rooms. We can add more as we want, these are the rooms that will be randomized when we generate a new game.
Note that these rooms still need to be filled with things.
> Basic level setup

- Assets/Art/Guns/AR.png.meta
- Assets/Art/Guns/Shotgun.png.meta
- Assets/Scenes/Lighting Room.unity
- Assets/Scenes/MainMenu.unity
- Assets/Scripts/Weapons/Data/AssaultRifle.asset
- Assets/Scripts/Weapons/Data/Shotgun.asset
The main menu was moving to a scene we aren't using and certain weapons are too far away, causing the player to be unable to shoot at enemies near the player.
> Menu and Weapon Quick Change

- Assets/Scripts/Weapons/Data/AssaultRifle.asset
- Assets/Scripts/Weapons/Data/WeaponData.cs
- Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
> Bouncing Bullets

- Assets/Scripts/Player/PlayerHealth.cs
- Assets/Scripts/Scene/AsyncSceneLoader.cs
Closes #186.
Turns out this is one instance was not a good application of the async loader.
> Dying goes to main menu

- Docs/MapBlockDiagram.md
- README.md
> Map Generation Block Diagram

- .clang-format
- Assets/Scripts/Audio/MusicPlayer.cs
- Assets/Scripts/Dialogue/DialogueManager.cs
- Assets/Scripts/Enemies/Boss/BossAnimator.cs
- Assets/Scripts/Enemies/Boss/BossDialogueManager.cs
- Assets/Scripts/Enemies/Boss/BossPhaseManager.cs
- Assets/Scripts/Map/MapNode.cs
- Assets/Scripts/Map/MapPlayerTracker.cs
- Assets/Scripts/Room/EnemySpawner.cs
- Assets/Scripts/UI/OverlayInformationController.cs
- Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
Pretty self explanatory, we briefly talked about it at some point.
> Updated formatting for `switch` statements

- Assets/Prefabs/Pistol Explosion.prefab
- Assets/Prefabs/Pistol Explosion.prefab.meta
- Assets/Scripts/Weapons/Data/Pistol.asset
- Assets/Scripts/Weapons/Data/WeaponData.cs
- Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
> Bullet explosion effect

- Docs/ChangeLog.md
Since we have given up on keeping track of stuff on the last day here is the final changelog for the season.
Closes #173.
> Sprint 8 changelog
